### ISSUE TITLE
Qualitative results

### ISSUE THREAD

**Issue by rongtongxueya** [HakamShams/LOAN#1]
![image](https://github.com/HakamShams/LOAN/assets/97833507/8535dd22-50cc-494b-b067-f874a7c7a5e0)

Fantastic work! I am curious about how you performed this visualization(eg.  Fig. 6.). Is there any code available for reference?

**Comment by HakamShams** [comment]
Hi, the scripts for visualization are **hard-coded**. You have to modify them so it can work for you.
However, I have attached the scripts which can be used to reproduce the figure above. Basically, you have to define a new dataloader (_FireCube_daily_) for the daily data. This should read directly from the datacube i.e., "dataset_greece_v1.0.nc" not from the preprocessed files. Then you can use the script (_test_daily_) to do prediction on a daily basis and store the results in a numpy array. Finally, you can use the script (_plot_daily_) to plot the results.
[FireCube_daily.zip](https://github.com/HakamShams/LOAN/files/14694255/FireCube_daily.zip)

**Comment by indraraj493** [comment]
and how can we get this "dataset_greece_v1.0.nc"  file

**Comment by HakamShams** [comment]
You can download the datacube from https://zenodo.org/records/6475592
